name: Continious Delivery

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.AUTO_RELEASE_GITHUB_TOKEN }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    - name: Build and push image
      uses: docker/build-push-action@v4
      with:
        context: ./EngineBay.CommunityEdition/
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{  github.ref_name }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          VERSION=${{  github.ref_name }}
